
tasks:
  - name: utils
    before: |
      sudp apt-get install tree
  - name: aws-cli
  
  #Inclusion of autoprompt for AWS CLI Ctr-C close
    env: 
      aws_cli_auto_prompt: on-partial 

  #Install the latest Amazon CLI utilizing linux curl installation
    before: | #| is yaml syntax
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

#export AWS_ACCESS_KEY_ID=your_access_key_id
#export AWS_SECRET_ACCESS_KEY=your_secret_access_key
#export AWS_DEFAULT_REGION='us-east-1'