#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-simple"
# Sets the name of the CloudFormation stack to be deployed.

aws cloudformation deploy \
  --template-file template.yaml \  # Specifies the CloudFormation template file.
  --no-execute-changeset \         # Creates a changeset but doesn't execute it, for review.
  --region us-east-1 \              # Sets the AWS region for the deployment.
  --stack-name $STACK_NAME         # Sets the stack name for the deployment.