#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN" 

STACK_NAME="cfn-s3-simple" # Set the CloudFormation stack name.

aws cloudformation delete-stack \
    --stack-name $STACK_NAME
# Delete the specified CloudFormation stack.
